#ifndef ERROR_HANDLER_H
#define ERROR_HANDLER_H

#include <stdio.h>

#define MAX_LINE_LENGTH 81 /* max 80 chars for line, +1 for terminator */
#define MAX_LABEL_LENGTH 32 /*max 31 chars for label, +1 for terminator */
#define MAX_STRING_LENGTH 12 /*max 11 chars for string, +1 for terminator */



enum {OK = 0, LINE_INVALID_LENGTH, LABEL_INVALID_LENGTH, LABEL_INVALID_INITIAL, LABEL_INVALID, LABEL_NO_ENDING_COLON, \
      DIRECTIVE_UNRECOGNIZED, EXTRANEOUS_OPERAND, MISPLACED_COMMA_START, MISPLACED_COMMA_END, MISSING_PARAM,    \
      CONSECUTIVE_COMMA, INVALID_PARAM, NUM_OUT_OF_RANGE, OUT_OF_MEMORY, INVALID_STRING, STRING_INVALID_LENGTH , LABEL_EQUAL_TO_SAVE_WORD , LABEL_WITHOUT_DIRECTIVE_OR_INSTRUCTION , LABEL_ALREADY_DEFINED ,NAME_FUNCTION_UNRECOGNIZE,
      INVALID_REGISTER , MISSING_COMMA , SET_ENTRY_TO_LABEL_UNDEFINED , COMMAND_WRONG_ORDER ,INVALID_COMMA
	, STRING_NOT_IN_QUOTE}; 


void print_error(const int error_num, const char * file_n, const int line_num, const char * token);

#endif 
